/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_andrescruz;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MBanegas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_addbus = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_idbus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_placabus = new javax.swing.JTextField();
        bt_colorbus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        js_velbus = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jb_agregarbus = new javax.swing.JButton();
        jd_addestudiante = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreestudiante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        js_edad = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        tf_cuenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_paradaestudiantes = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jd_addparadas = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nombreparada = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        js_distanciaparada = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        js_angulo = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_resumen = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        addestudiantes = new javax.swing.JButton();
        addbus = new javax.swing.JButton();
        pb_recorrido = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        bt_iniciarrecorrido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Autobus");

        jLabel4.setText("Identificacion:");

        jLabel5.setText("Placa:");

        bt_colorbus.setBackground(new java.awt.Color(255, 102, 102));
        bt_colorbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorbusMouseClicked(evt);
            }
        });

        jLabel6.setText("Color:");

        jLabel7.setText("Velocidad:");

        js_velbus.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 320.0d, 1.0d));

        jLabel8.setText("KM/H");

        jb_agregarbus.setText("Agregar");
        jb_agregarbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarbusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_addbusLayout = new javax.swing.GroupLayout(jd_addbus.getContentPane());
        jd_addbus.getContentPane().setLayout(jd_addbusLayout);
        jd_addbusLayout.setHorizontalGroup(
            jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_addbusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_agregarbus)
                    .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_colorbus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_idbus, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(tf_placabus))
                    .addGroup(jd_addbusLayout.createSequentialGroup()
                        .addComponent(js_velbus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jd_addbusLayout.setVerticalGroup(
            jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_addbusLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_idbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_placabus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bt_colorbus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_velbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addComponent(jb_agregarbus)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agregar Estudiante");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Edad:");

        js_edad.setModel(new javax.swing.SpinnerNumberModel(15, 14, 150, 1));

        jLabel12.setText("Cuenta:");

        jLabel13.setText("Parada:");

        jButton3.setText("Agregar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_addestudianteLayout = new javax.swing.GroupLayout(jd_addestudiante.getContentPane());
        jd_addestudiante.getContentPane().setLayout(jd_addestudianteLayout);
        jd_addestudianteLayout.setHorizontalGroup(
            jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .addGroup(jd_addestudianteLayout.createSequentialGroup()
                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_addestudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_addestudianteLayout.createSequentialGroup()
                                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_addestudianteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tf_cuenta))
                            .addGroup(jd_addestudianteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cb_paradaestudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jd_addestudianteLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_addestudianteLayout.setVerticalGroup(
            jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_addestudianteLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_paradaestudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Agregar Parada");

        jLabel15.setText("Nombre:");

        jLabel16.setText("Distancia:");

        js_distanciaparada.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        jLabel17.setText("KM");

        jLabel18.setText("Angulo:");

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        js_angulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 360.0d, 1.0d));

        jLabel19.setText("Grados");

        javax.swing.GroupLayout jd_addparadasLayout = new javax.swing.GroupLayout(jd_addparadas.getContentPane());
        jd_addparadas.getContentPane().setLayout(jd_addparadasLayout);
        jd_addparadasLayout.setHorizontalGroup(
            jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
            .addGroup(jd_addparadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_addparadasLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreparada, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_addparadasLayout.createSequentialGroup()
                        .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_addparadasLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(js_angulo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_addparadasLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(js_distanciaparada, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_addparadasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(93, 93, 93))
        );
        jd_addparadasLayout.setVerticalGroup(
            jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_addparadasLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombreparada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(js_distanciaparada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jd_addparadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(js_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_resumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parada", "Tiempo", "Estudiante"
            }
        ));
        jScrollPane1.setViewportView(tab_resumen);

        jButton1.setText("Agregar Paradas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        addestudiantes.setText("Agregar Estudiantes");
        addestudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addestudiantesMouseClicked(evt);
            }
        });

        addbus.setText("Agregar Autobuses");
        addbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbusMouseClicked(evt);
            }
        });

        pb_recorrido.setToolTipText("");
        pb_recorrido.setString("");
        pb_recorrido.setStringPainted(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recorrido Bus");

        bt_iniciarrecorrido.setText("Iniciar Recorrido");
        bt_iniciarrecorrido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarrecorridoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Simulación AutoBuses UNITEC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pb_recorrido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addestudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addbus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_iniciarrecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_iniciarrecorrido))
                .addGap(18, 18, 18)
                .addComponent(pb_recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbus)
                        .addGap(18, 18, 18)
                        .addComponent(addestudiantes)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_colorbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorbusMouseClicked
        // TODO add your handling code here:
        bt_colorbus.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_colorbusMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbusMouseClicked
        // TODO add your handling code here:
        jd_addbus.setLocationRelativeTo(this);
        jd_addbus.setModal(true);
        jd_addbus.pack();
        jd_addbus.setVisible(true);
    }//GEN-LAST:event_addbusMouseClicked

    private void jb_agregarbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarbusMouseClicked
        // TODO add your handling code here:
        boolean entrar = true;
        if (tf_idbus.getText().equals("") || tf_placabus.getText().equals("")) {
            entrar = false;
        }
        if (entrar) {
            try {
                String id = tf_idbus.getText();
                String placa = tf_placabus.getText();
                Color color = bt_colorbus.getBackground();
                Double velocidad = (Double) js_velbus.getValue();
                buses.add(new Autobus(id, placa, color, velocidad));
                haybuses = true;
                JOptionPane.showMessageDialog(jd_addbus, "Se agrego de manera exitosa!");
                tf_idbus.setText("");
                tf_placabus.setText("");
                bt_colorbus.setBackground(Color.red);
                js_velbus.setValue(0);
                jd_addbus.dispose();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(jd_addbus, "Hay campos vacios!");
        }

    }//GEN-LAST:event_jb_agregarbusMouseClicked

    private void addestudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addestudiantesMouseClicked
        // TODO add your handling code here:
        if (hayparadas) {
            jd_addestudiante.setLocationRelativeTo(this);
            jd_addestudiante.setModal(true);
            jd_addestudiante.pack();
            jd_addestudiante.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay paradas disponibles, cree una parada primero.");
        }
    }//GEN-LAST:event_addestudiantesMouseClicked

    public boolean validacioncuenta(String cuenta) {
        int cont = 0;
        for (int i = 0; i < cuenta.length(); i++) {
            if (Character.isDigit(cuenta.charAt(i))) {
                cont++;
            }
        }
        if (cont == cuenta.length()) {
            return false;
        } else {
            return true;
        }
    }

    public boolean validacionunica(String cuenta) {
        for (int i = 0; i < estudiantes.size(); i++) {
            if (estudiantes.get(i).getCuenta().equals(cuenta)) {
                return true;
            }
        }
        return false;
    }

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        boolean entrar = true;
        if (tf_nombreestudiante.getText().equals("") || tf_cuenta.getText().equals("") || validacioncuenta(tf_cuenta.getText()) || validacionunica(tf_cuenta.getText())) {
            entrar = false;
        }
        if (entrar) {
            try {
                String nombre = tf_nombreestudiante.getText();
                String cuenta = tf_cuenta.getText();
                Parada parada = (Parada) cb_paradaestudiantes.getSelectedItem();
                int edad = (Integer) js_edad.getValue();
                estudiantes.add(new Estudiante(nombre, edad, cuenta, parada));
                hayestudiantes = true;
                JOptionPane.showMessageDialog(jd_addestudiante, "Se agrego de manera exitosa!");
                tf_nombreestudiante.setText("");
                tf_cuenta.setText("");
                cb_paradaestudiantes.setSelectedIndex(0);
                js_edad.setValue(15);
                jd_addestudiante.dispose();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(jd_addestudiante, "Hay campos vacios!");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_addparadas.setModal(true);
        jd_addparadas.setLocationRelativeTo(this);
        jd_addparadas.pack();
        jd_addparadas.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        boolean entrar = true;
        if (tf_nombreparada.getText().equals("")) {
            entrar = false;
        }
        if (entrar) {
            try {
                String nombre = tf_nombreparada.getText();
                Double distancia = (Double) js_distanciaparada.getValue();
                Double angulo = Math.toRadians((Double) js_angulo.getValue());
                paradas.add(new Parada(nombre, distancia, angulo));
                paradas_rep.add(new Parada(nombre, distancia, angulo));
                hayparadas = true;
                JOptionPane.showMessageDialog(jd_addparadas, "Se agrego de manera exitosa!");
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_paradaestudiantes.getModel();
                modelo.addElement(paradas.get(paradas.size() - 1));
                cb_paradaestudiantes.setModel(modelo);
                tf_nombreparada.setText("");
                js_distanciaparada.setValue(1);
                js_angulo.setValue(0);
                jd_addparadas.dispose();
            } catch (Exception e) {
            }

        } else {
            JOptionPane.showMessageDialog(jd_addestudiante, "Hay campos vacios!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void bt_iniciarrecorridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarrecorridoMouseClicked
        // TODO add your handling code here:
        
            if (haybuses && hayestudiantes && hayparadas) {
                ArrayList<Estudiante> est = new ArrayList();
                for (int i = 0; i < estudiantes.size(); i++) {
                    est.add(estudiantes.get(i));
                }
                String imprimir = "";
                for (int i = 0; i < buses.size(); i++) {
                    imprimir += i + " - " + buses.get(i) + "\n";
                }
                try {
                    int pos = Integer.parseInt(JOptionPane.showInputDialog(imprimir + "Ingrese la posicion del bus que desea usar: "));
                    boolean flag = true;
                    while (flag) {
                        imprimir = "";
                        for (int i = 0; i < est.size(); i++) {
                            imprimir += i + " - " + est.get(i) + "\n";
                        }
                        if (!est.isEmpty()) {
                            int opt = Integer.parseInt(JOptionPane.showInputDialog(imprimir + "Ingrese la posicion del estudiante que desea agregar:"));
                            buses.get(pos).getEstudiantes().add(est.get(opt));
                            est.remove(opt);
                            int opc = Integer.parseInt(JOptionPane.showInputDialog("Ingrese 1 para salir y otro numero para seguir y agregar otro estudiante:"));
                            if (opc == 1) {
                                flag = false;
                            }
                        } else {
                            flag = false;
                        }

                    }
                    Recorrido rec = new Recorrido(pb_recorrido, puederecorrer, buses.get(pos), paradas, tab_resumen);
                    Thread a = new Thread(rec);
                    a.start();
                    puederecorrer = false;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error!");                    
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cree buses, estudiantes y paradas para usar esta opcion!");
            }
    }//GEN-LAST:event_bt_iniciarrecorridoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbus;
    private javax.swing.JButton addestudiantes;
    private javax.swing.JButton bt_colorbus;
    private javax.swing.JButton bt_iniciarrecorrido;
    private javax.swing.JComboBox<String> cb_paradaestudiantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton jb_agregarbus;
    private javax.swing.JDialog jd_addbus;
    private javax.swing.JDialog jd_addestudiante;
    private javax.swing.JDialog jd_addparadas;
    private javax.swing.JSpinner js_angulo;
    private javax.swing.JSpinner js_distanciaparada;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JSpinner js_velbus;
    private javax.swing.JProgressBar pb_recorrido;
    private javax.swing.JTable tab_resumen;
    private javax.swing.JTextField tf_cuenta;
    private javax.swing.JTextField tf_idbus;
    private javax.swing.JTextField tf_nombreestudiante;
    private javax.swing.JTextField tf_nombreparada;
    private javax.swing.JTextField tf_placabus;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Estudiante> estudiantes = new ArrayList();
    private ArrayList<Parada> paradas = new ArrayList();
    private ArrayList<Parada> paradas_rep = new ArrayList();
    private ArrayList<Autobus> buses = new ArrayList();
    private boolean hayparadas = false;
    private boolean haybuses = false;
    private boolean hayestudiantes = false;
    private boolean puederecorrer = true;
}
